######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 30 10:51:45 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += noteHandler.h
SOURCES += main.cxx noteHandler.cxx
