######################################################################
# Automatically generated by qmake (2.01a) Wed May 11 18:47:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -L/usr/lib/ -lmarkdown
#CONFIG += debug

# Input
HEADERS += noteHandler.h
SOURCES += main.cxx noteHandler.cxx
